In [71]:
import pandas as pd
df = pd.read_csv("./data/Wednesday-workingHours.pcap_ISCX.csv")

In [72]:
data = df

In [73]:
data.shape

(692703, 79)

In [74]:
data

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,38308,1,1,6,6,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,389,479,11,5,172,326,79,0,15.636364,31.449238,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,88,1095,10,6,3150,3150,1575,0,315.000000,632.561635,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,389,15206,17,12,3452,6660,1313,0,203.058823,425.778474,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,88,1092,9,6,3150,3152,1575,0,350.000000,694.509719,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692698,53,32215,4,2,112,152,28,28,28.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692699,53,324,2,2,84,362,42,42,42.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692700,58030,82,2,1,31,6,31,0,15.500000,21.920310,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692701,53,1048635,6,2,192,256,32,32,32.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692702,53,94939,4,2,188,226,47,47,47.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692703 entries, 0 to 692702
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             692703 non-null  int64
 1    Flow Duration                692703 non-null  int64
 2    Total Fwd Packets            692703 non-null  int64
 3    Total Backward Packets       692703 non-null  int64
 4   Total Length of Fwd Packets   692703 non-null  int64
 5    Total Length of Bwd Packets  692703 non-null  int64
 6    Fwd Packet Length Max        692703 non-null  int64
 7    Fwd Packet Length Min        692703 non-null  int64
 8    Fwd Packet Length Mean       692703 non-null  float64
 9    Fwd Packet Length Std        692703 non-null  float64
 10  Bwd Packet Length Max         692703 non-null  int64
 11   Bwd Packet Length Min        692703 non-null  int64
 12   Bwd Packet Length Mean       692703 non-null  float64
 13   Bwd Packet Length Std        692703 non-null  float64
 14  Flow Bytes/s                  691695 non-null  float64
 15   Flow Packets/s               692703 non-null  float64
 16   Flow IAT Mean                692703 non-null  float64
 17   Flow IAT Std                 692703 non-null  float64
 18   Flow IAT Max                 692703 non-null  int64
 19   Flow IAT Min                 692703 non-null  int64
 20  Fwd IAT Total                 692703 non-null  int64
 21   Fwd IAT Mean                 692703 non-null  float64
 22   Fwd IAT Std                  692703 non-null  float64
 23   Fwd IAT Max                  692703 non-null  int64
 24   Fwd IAT Min                  692703 non-null  int64
 25  Bwd IAT Total                 692703 non-null  int64
 26   Bwd IAT Mean                 692703 non-null  float64
 27   Bwd IAT Std                  692703 non-null  float64
 28   Bwd IAT Max                  692703 non-null  int64
 29   Bwd IAT Min                  692703 non-null  int64
 30  Fwd PSH Flags                 692703 non-null  int64
 31   Bwd PSH Flags                692703 non-null  int64
 32   Fwd URG Flags                692703 non-null  int64
 33   Bwd URG Flags                692703 non-null  int64
 34   Fwd Header Length            692703 non-null  int64
 35   Bwd Header Length            692703 non-null  int64
 36  Fwd Packets/s                 692703 non-null  float64
 37   Bwd Packets/s                692703 non-null  float64
 38   Min Packet Length            692703 non-null  int64
 39   Max Packet Length            692703 non-null  int64
 40   Packet Length Mean           692703 non-null  float64
 41   Packet Length Std            692703 non-null  float64
 42   Packet Length Variance       692703 non-null  float64
 43  FIN Flag Count                692703 non-null  int64
 44   SYN Flag Count               692703 non-null  int64
 45   RST Flag Count               692703 non-null  int64
 46   PSH Flag Count               692703 non-null  int64
 47   ACK Flag Count               692703 non-null  int64
 48   URG Flag Count               692703 non-null  int64
 49   CWE Flag Count               692703 non-null  int64
 50   ECE Flag Count               692703 non-null  int64
 51   Down/Up Ratio                692703 non-null  int64
 52   Average Packet Size          692703 non-null  float64
 53   Avg Fwd Segment Size         692703 non-null  float64
 54   Avg Bwd Segment Size         692703 non-null  float64
 55   Fwd Header Length.1          692703 non-null  int64
 56  Fwd Avg Bytes/Bulk            692703 non-null  int64
 57   Fwd Avg Packets/Bulk         692703 non-null  int64
 58   Fwd Avg Bulk Rate            692703 non-null  int64
 59   Bwd Avg Bytes/Bulk           692703 non-null  int64
 60   Bwd Avg Packets/Bulk         692703 non-null  int64
 61  Bwd Avg Bulk Rate             692703 non-null  int64
 62  Subflow Fwd Packets           692703 non-null  int64
 63   Subflow Fwd Bytes            692703 non-null  int64
 64   Subflow Bwd Packets          692703 non-null  int64
 65   Subflow Bwd Bytes            692703 non-null  int64
 66  Init_Win_bytes_forward        692703 non-null  int64
 67   Init_Win_bytes_backward      692703 non-null  int64
 68   act_data_pkt_fwd             692703 non-null  int64
 69   min_seg_size_forward         692703 non-null  int64
 70  Active Mean                   692703 non-null  float64
 71   Active Std                   692703 non-null  float64
 72   Active Max                   692703 non-null  int64
 73   Active Min                   692703 non-null  int64
 74  Idle Mean                     692703 non-null  float64
 75   Idle Std                     692703 non-null  float64
 76   Idle Max                     692703 non-null  int64
 77   Idle Min                     692703 non-null  int64
 78   Label                        692703 non-null  object
dtypes: float64(24), int64(54), object(1)
memory usage: 417.5+ MB

In [101]:
data.describe().astype(float)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,691055.000000,6.910550e+05,691055.000000,691055.000000,6.910550e+05,6.910550e+05,691055.000000,691055.000000,691055.000000,691055.000000,...,691055.000000,691055.000000,6.910550e+05,6.910550e+05,6.910550e+05,6.910550e+05,6.910550e+05,6.910550e+05,6.910550e+05,6.910550e+05
mean,5685.616020,2.802478e+07,9.522549,10.238055,5.564119e+02,1.703697e+04,234.146987,15.055512,60.696595,83.092475,...,6.135739,26.768722,9.036744e+04,4.570502e+04,1.575915e+05,6.310230e+04,2.215881e+07,4.740139e+05,2.256783e+07,2.178186e+07
std,15725.295717,4.276664e+07,748.083305,985.377358,6.170949e+03,2.243846e+06,604.364926,51.124956,157.805027,226.359621,...,716.007236,6.298027,6.912155e+05,4.601660e+05,1.049218e+06,6.048934e+05,3.815542e+07,4.492854e+06,3.851471e+07,3.810842e+07
min,21.000000,1.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,-1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,53.000000,2.020000e+02,2.000000,1.000000,1.200000e+01,0.000000e+00,6.000000,0.000000,6.000000,0.000000,...,0.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,80.000000,6.154000e+04,2.000000,2.000000,8.200000e+01,1.880000e+02,46.000000,0.000000,41.000000,0.000000,...,1.000000,32.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,443.000000,8.305927e+07,7.000000,6.000000,3.650000e+02,1.159500e+04,341.000000,33.000000,56.833333,129.114567,...,2.000000,32.000000,9.910000e+02,0.000000e+00,9.910000e+02,9.890000e+02,1.600000e+07,0.000000e+00,1.800000e+07,1.000000e+07
max,65487.000000,1.200000e+08,203943.000000,272353.000000,1.224076e+06,6.270000e+08,24820.000000,2065.000000,4640.757576,6429.190773,...,197124.000000,60.000000,1.000000e+08,7.420000e+07,1.050000e+08,1.000000e+08,1.200000e+08,7.690000e+07,1.200000e+08,1.200000e+08

In [77]:
data[" Label"].unique()

array(['BENIGN', 'DoS slowloris', 'DoS Slowhttptest', 'DoS Hulk',
       'DoS GoldenEye', 'Heartbleed'], dtype=object)

# limpieza
hemos visto que pese a no haver valores nulos, hay valores irreales que han de ser limpiados como los valores 'inf' o lo spuertos '0.00'

> Añadir blockquote

In [78]:
data[data[" Flow Packets/s"]==float("inf")][" Label"].value_counts()

 Label
DoS Hulk    949
BENIGN      348
Name: count, dtype: int64

In [79]:
for n,m in data[[" Flow Packets/s", " Label"]].iterrows():
  if n == float('inf') and m == 'Benign':
    print(n,m)

In [80]:
data = data.drop(df[df[" Flow Packets/s"] == float('inf')].index)

In [102]:
data[data[" Flow Packets/s"]==float("inf")][" Label"].value_counts()

Series([], Name: count, dtype: int64)

In [82]:
data[data[" Destination Port"]==float("0.00")][" Label"].value_counts()

 Label
BENIGN    330
Name: count, dtype: int64

In [83]:
for n,m in data[[" Destination Port", " Label"]].iterrows():
  if n == '0.00' and m == 'Benign':
    print(n,m)

In [84]:
data = data.drop(df[df[" Destination Port"] == float('0.00')].index)

In [85]:
data[data[" Destination Port"]==float("0.00")][" Label"].value_counts()

Series([], Name: count, dtype: int64)

In [86]:
valores_unicos = df[" Flow Duration"].unique().tolist()
for valor in valores_unicos:
    if valor <= 0:
      print(valor)

0
-1

In [87]:
data[data[" Flow Duration"]<= float("0")][" Label"].value_counts()

 Label
BENIGN    21
Name: count, dtype: int64

In [88]:
data = data.drop(df[df[" Flow Duration"] == float('-1')].index)

In [89]:
data[data[" Flow Duration"]<= float("0")][" Label"].value_counts()

Series([], Name: count, dtype: int64)

# columnas que se pueden eliminar

In [93]:
d1 = data.pop(' Fwd URG Flags')
d1 = data.pop(' Bwd URG Flags')
d1 = data.pop(' CWE Flag Count')
d1 = data.pop(' ECE Flag Count')

In [94]:
d2 = data.pop("Fwd Avg Bytes/Bulk")
d2 = data.pop(" Bwd Avg Bytes/Bulk")
d2 = data.pop(" Fwd Avg Packets/Bulk")

In [95]:
d3 = data.pop("Subflow Fwd Packets")
d3 = data.pop(" Subflow Bwd Packets")
d3 = data.pop(" Subflow Fwd Bytes")
d3 = data.pop(" Subflow Bwd Bytes")

In [96]:
data.shape

(691055, 68)

In [103]:
data.to_csv("datos_modificados.csv", index=False)